spring:
  application:
    name: franquicias-api
  
  r2dbc:
    url: ${DATABASE_URL:r2dbc:mysql://localhost:3306/franquicias_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root_password}
  
  flyway:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/franquicias_db}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root_password}
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
  
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/franquicias_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.accenture.franquicias: INFO