spring:
  application:
    name: franquicias-api  
 
  r2dbc:
    url: r2dbc:mysql://localhost:3306/franquicias_db
    username: root
    password: 
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m  
 
  flyway:
    url: jdbc:mysql://localhost:3306/franquicias_db
    user: root
    password: 
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.accenture.franquicias: DEBUG
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
